version: 0.0
os: linux
files:
  - source: /.nuxt/
    destination: ~/app/.nuxt
  - source: /static/
    destination: ~/app/static
  - source: /package.json
    destination: ~/app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
